server:
  port: 9001

spring:
  application:
    name: flashcards
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/flashcardsDB
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
